### ISSUE TITLE
refactoring / rebuild: simplify!!!

### ISSUE THREAD

**Issue by jonmorehouse** [jonmorehouse/vim-flow#11]
It seems to me like we can simplify this module drastically. Specifically, let's create the concept of a `.flow.yml` which declares all of the logic to handle a specific file runner.

A sample file looks like:

```yaml
all: 
   tmux_pane: 1
   tmux_session: 0
   cmd: |
       echo {{filename}}

py: 
  cmd: |
       echo {{filename}}
```

It seems to me like we can make this stupid simple. VimFlow does the following:

* identifies the current file's extension
* walks up the directory path and fines the closest ".flow.yml"
* fetches the extension command or the "all" command and executes it

We can remove all of the builtin flows, in favor of having users specify a `.flow.yml`. This should automagically re-load each file each time (there is no caching, anywhere) and runs the command in either the current window or a background tmux window.

We'll support the following variable templates:

```python
templates = {
    "{{filename}}": os.path.abspath(filepath),
    "{{directory}}": os.path.dirname(filepath),
}
```

FWIW - we should still "lock" files, but it seems like almost everything else can go in favor of this simpler work flow.
