### ISSUE TITLE
support filename specific commands

### ISSUE THREAD

**Issue by jonmorehouse** [jonmorehouse/vim-flow#15]
Thinking through some of the previous workflows that I had, I think it's sometimes helpful to specify a command for a specific filename.

For instance, let's say you are working on a `Vagrantfile` and want to run a vagrant command as part of your dev/test flow, we could support something like:

```yaml
---
Vagrantfile:
     cmd: cd ~/vagrant && vagrant up

```
